[package]
name = "siwe-rs-capabilities"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.12"
iri-string = "0.4"
siwe = "0.3"
serde_json = "1"
thiserror = "1"

[dependencies.serde]
version = "1"
features = ["derive"]

