[package]
name = "capgrok"
description = "Build wallet-signable messages with capability delegations that are human- and machine-readable."
license = "Apache-2.0"
version = "0.2.2"
edition = "2021"
readme = "README.md"
repository = "https://github.com/spruceid/capgrok/"

[dependencies]
base64 = "0.12"
iri-string = "0.4"
siwe = "0.4"
serde_json = "1"
thiserror = "1"

[dependencies.serde]
version = "1"
features = ["derive"]

