[package]
name = "siwe-recap"
description = "EIP-5573: Mechanism on top of Sign-In with Ethereum for informed consent to delegate capabilities with an extensible scope mechanism."
license = "Apache-2.0"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/spruceid/siwe-recap/"

[dependencies]
base64 = "0.12"
iri-string = "0.4"
siwe = ">=0.4"
serde_json = "1"
thiserror = "1"

[dependencies.serde]
version = "1"
features = ["derive"]

